FROM centos:7.6.1810

COPY gosu-amd64 /usr/local/bin/gosu


ENV LANG en_US.utf8

RUN set -eux; \
    yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm && \
    yum install -y postgresql13-server && \
    yum install -y centos-release-scl-rh && \
    yum install -y devtoolset-7-gcc-c++  devtoolset-7-gcc perl libxml2-devel.x86_64 libtiff.x86_64 openssl-devel.x86_64 libuuid-devel && \
    yum install -y boost-thread.x86_64 boost-system.x86_64 boost-serialization.x86_64 boost-chrono.x86_64 boost-date-time.x86_64 boost-atomic.x86_64 && \
    yum clean all && \
    mkdir /docker-entrypoint-initdb.d 
   


ENV GOSU_VERSION 1.12
COPY yukon/extension/* /usr/pgsql-13/share/extension/
COPY yukon/lib/* /usr/pgsql-13/lib/
COPY yukon/yukon_dep/ /opt/3rd/

RUN set -eux; \
    chmod +x /usr/local/bin/gosu && \
    chown -R postgres:postgres /usr/pgsql-13/share/extension/ && \
    chown -R postgres:postgres /usr/pgsql-13/lib/ 


ENV PGDATA /var/lib/postgres/data
ENV PATH /usr/pgsql-13/bin/:$PATH
ENV LD_LIBRARY_PATH /usr/lib64/:/opt/3rd/ugc:/opt/3rd/cgal/lib64:/opt/3rd/cgal/lib:/opt/3rd/gdal/lib:/opt/3rd/geos/lib64:/opt/3rd/jsonc/lib64:/opt/3rd/libxml2/lib:/opt/3rd/proj/lib:/opt/3rd/sfcgal/lib64:/opt/3rd/misc/:$LD_LIBRARY_PATH


COPY entrypoint.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh;ln -s /usr/local/bin/entrypoint.sh / # backwards compat



ENTRYPOINT ["entrypoint.sh"]


EXPOSE 5432
CMD ["postgres"]

